tap "homebrew/cask" 

tap "d12frosted/emacs-plus"
brew "emacs-plus"

cask "anki"
cask "dropbox"
cask "alfred"
cask "bitwarden"
cask "docker"
cask "iterm2"
cask "google-chrome"
cask "spotify"
cask "shortcat"
cask "zulip"
cask "qutebrowser"
