#!/usr/bin/env sh

# labeling
yabai -m space 1 --label main

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_topmost               on
yabai -m config window_border                on
yabai -m config window_border_width          8
# not a thing, but I wish
# yabai -m config window_border_placement      inset
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xff00CC00
yabai -m config normal_window_border_color   0xff000000
yabai -m config split_ratio                  0.66
yabai -m config auto_balance                 on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5


# rules
yabai -m rule --add app='System Preferences' manage=off

echo "yabai configuration loaded.."
